import Select from '../components/Select';
import { Controller, Product, Filter, FilterCheckboxType } from '../types';
import { Option } from '../types/index';
export declare class MainController extends Controller {
    products: Product[];
    filteredProducts: Product[];
    optionsSort: Option[];
    selected: Option;
    optionsView: Option[];
    selectSort: Select | null;
    selectedView: Option;
    search: string;
    filter: Filter;
    filterData: Filter;
    isPriceChanged: boolean;
    isStockChanged: boolean;
    setURLParams(param: string, value: string): void;
    getURLParams(): void;
    onSearchInputHandler(value: string): void;
    init(): Promise<void>;
    onPriceRangeHandler(value: [number, number]): void;
    onStockRangeHandler(value: [number, number]): void;
    filterProducts(): void;
    getFoundCount(): void;
    getFilter(): void;
    renderFilter(): void;
    renderFilterList(arr: string[], root: Element, type: FilterCheckboxType): void;
    onChangeViewHandler(select: Select, option: Option): void;
    getData(list: HTMLElement): Promise<void>;
    setLoading(root: HTMLElement): void;
    onSortClickHandler(select: Select, option: Option): void;
    renderProducts(root: HTMLElement): Promise<void>;
}
